source "http://rubygems.org"

gem "nats"
gem "uuidtools"
gem "thin"
gem "sinatra"
gem "redis"
gem "rake"
gem "sys-filesystem"

gem 'vcap_common', '>= 1.0.8', :require => ['vcap/common', 'vcap/component']
gem 'vcap_logging', '>=0.1.3', :require => ['vcap/logging']

group :test do
  gem "rspec"
  gem "rack-test"
  gem "rcov"
  gem "simplecov"
  gem "simplecov-rcov"
  gem "ci_reporter"
end
