source :rubygems

gem 'eventmachine'
gem "em-http-request"
gem "nats"
gem "ruby-hmac"
gem "uuidtools"
gem "datamapper", ">= 0.10.2"
gem "do_sqlite3"
gem "dm-sqlite-adapter"
gem "sinatra"
gem "thin"
gem "json"
gem "sys-filesystem"
gem "yajl-ruby"

gem 'vcap_common', '~> 1.0.8', :require => ['vcap/common', 'vcap/component']
gem 'vcap_logging', '>=1.0.2', :require => ['vcap/logging']
gem 'vcap_services_base'

group :test do
  gem "rake"
  gem "rspec"
  gem "simplecov"
  gem "simplecov-rcov"
  gem "ci_reporter"
end
