source :rubygems

gem "datamapper", ">= 0.10.2"
gem "dm-sqlite-adapter"
gem "do_sqlite3"
gem "eventmachine"
gem "em-http-request"
gem "nats"
gem "ruby-hmac"
gem "uuidtools"
gem "rest-client"
gem "sinatra"
gem "thin"

gem 'vcap_common', '>= 1.0.8', :require => ['vcap/common', 'vcap/component']
gem 'vcap_logging', '>=0.1.3', :require => ['vcap/logging']
gem "vcap_services_base"

group :test do
  gem "rake"
  gem "rspec"
  gem "rcov"
  gem "ci_reporter"
end
