source "http://rubygems.org"

gem "nats"
gem "datamapper", ">= 0.10.2"
gem "do_sqlite3", :require => nil
gem "dm-sqlite-adapter"
gem 'eventmachine'
gem "em-http-request"
gem "json"
gem "pg"
gem "uuidtools"
gem "ruby-hmac", :require => "hmac-sha1"
gem "thin"
gem "sinatra"

gem 'vcap_common', '~> 1.0.8', :require => ['vcap/common', 'vcap/component']
gem 'vcap_logging', '>=0.1.3', :require => ['vcap/logging']
gem "vcap_services_base"

group :test do
  gem "rake"
  gem "rspec"
  gem "rcov"
  gem "simplecov"
  gem "simplecov-rcov"
  gem "ci_reporter"
end
