source "http://rubygems.org"

gem "nats", '>= 0.4.8'
gem "datamapper", ">= 0.10.2"
gem "do_sqlite3", :require => nil
gem "dm-sqlite-adapter"
gem "eventmachine"
gem "em-http-request"
gem "json"
gem "pg"
gem "uuidtools"
gem "ruby-hmac", :require => "hmac-sha1"
gem "thin"
gem "sinatra"

gem 'vcap_common', :path => '../../common'

group :test do
  gem "rake"
  gem "rspec"
  gem "rcov"
  gem "ci_reporter"
end

