source "http://rubygems.org"

gem 'eventmachine'
gem 'em-http-request'
gem 'json'
gem 'yajl-ruby'

group :test do
  gem 'rspec', '>= 2.4.0', :require => nil
  gem 'rcov'
  gem 'mocha'
  gem 'ci_reporter'
  gem 'sinatra'
  gem "thin"
end
