source :rubygems

gem "rake"
gem "rack"
gem "rack-proxy"
gem "sinatra"
gem "sinatra-contrib"
gem "yajl-ruby"
gem "omniauth-uaa-oauth2", :git => "git://github.com/cloudfoundry/omniauth-uaa-oauth2.git", :ref => "ffa3468e93"
gem "vcap_logging", :require => ["vcap/logging"], :git => "git://github.com/cloudfoundry/common.git", :ref => "b96ec1192"
gem "cfoundry", :git => "git://github.com/cloudfoundry/vmc-lib.git", :submodules => true

group :test do
  gem "rack-test"
  gem "rspec"
end
