source :rubygems

gem 'eventmachine',  '~> 0.12.11.cloudfoundry.3'
gem "em-http-request"
gem "nats", '>= 0.4.10'
gem "ruby-hmac"
gem "uuidtools"
gem "datamapper", ">= 0.10.2"
gem "do_sqlite3"
gem "dm-sqlite-adapter"
gem "sinatra"
gem "resque-status", "~> 0.2.4"
gem "resque", "~> 1.19.0"
gem "thin"
gem "mongo"
gem "bson_ext"

gem 'vcap_common', :require => ['vcap/common', 'vcap/component']
gem 'vcap_logging', '>=0.1.3', :require => ['vcap/logging']
gem "vcap_services_base", '~> 0.1.3'

group :test do
  gem "rake"
  gem "rspec"
  gem "rcov"
  gem "ci_reporter"
end
