source "https://rubygems.org"

gem "cf-uaa-lib"
gem "rspec"
gem "nats"
gem "yajl-ruby"
gem "httpclient"
gem "sinatra"
gem "vcr"
gem "webmock"
gem "httpclient"
gem "rake"
gem "sequel"
gem "mysql2"

gem "debugger", group: :test
