require 'rake'
require 'yaml'
require 'yajl'

desc "Run specs"
task "spec" => ["test:spec"]

desc "Run specs using SimpleCov"
task "spec:rcov" => ["test:spec:rcov"]

desc "Run ci using SimpleCov"
task "spec:ci" => ["test:spec:ci"]

namespace "bundler" do
  desc "Install gems"
  task "install" do
    sh("bundle install")
  end

  desc "Install gems for test"
  task "install:test" do
    sh("bundle install --without development production")
  end

  desc "Install gems for production"
  task "install:production" do
    sh("bundle install --without development test")
  end

  desc "Install gems for development"
  task "install:development" do
    sh("bundle install --without test production")
  end
end

namespace "test" do
  def run_spec
    sh "nats-server &"
    Dir.chdir("spec"){ yield }
    sh "pkill -f nats-server"
  end

  def run_or_fail(cmd)
    raise "Failed to run '#{cmd}'" unless system(cmd)
  end

  task "spec" do |t|
    run_spec { run_or_fail "rake spec --trace" }
  end

  task "spec:rcov" do |t|
    run_spec { run_or_fail "rake simcov --trace" }
  end

  task "spec:ci" do |t|
    run_spec { run_or_fail "rake spec:ci --trace" }
  end
end
